server:
  port: 7002

#eoueka配置
eureka:
  instance:
    hostname: localhost #eureka 服务端的实例名称
  client:
    register-with-eureka: true #表示是否向eureka注册中心注册自己
    fetch-registry: true #fetch-registry如果为了false 则表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
