server:
  port: 80
#  Eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-engistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
